#!/bin/bash
if [ $(top -bn1 | grep "yump" | wc -l) -gt 2 ]
then
  exit 0
fi

cd $HOME/.config/yump
id=$(cmus-remote --query | head -n 2 | tail -n 1 | sed 's/.*\(.\{11\}\).mp3/\1/')
file=$(grep -H -- "$id" channels/* | head -n 1 | awk -F ":" '{print $1}')
sed -i "s/$id \(0\|1\|-1\)/$id 1/g" $file
nameWidthId=$(cmus-remote --query | head -n 2 | tail -n 1 | sed 's/file //g')
name=$(cmus-remote --query | head -n 2 | tail -n 1 | sed "s|file ||g;s|-$id||g;s|$HOME/.config/yump/audio-tmp/||g")
playlist=$(echo $file | awk -F "/" '{print $2}') 

next=$(ls -tr1 "channels/" | head -n 1 | tail -n 1)
count=$(ls -tr1 channels | wc -l)
for (( i=1; i <=$count; i++ ))
do
  if [ $(grep " 0" "channels/$next" | wc -l) -gt 0 ]
  then
    break
  fi
  next=$(ls -tr1 "channels/" | head -n $i | tail -n 1)
done
cp "$nameWidthId" "$HOME/Music/$playlist/$name"
notify-send "Song liked!" "Next channel: $next"


# This should trigger when liked song ended
# change sleep to something more reliable
duration=$(cmus-remote --query | head -n 3 | tail -n 1 | awk '{print $2}')
position=$(cmus-remote --query | head -n 4 | tail -n 1 | awk '{print $2}')
sleep $(( $duration-$position-1 ))
yump-get
